# Example of a custom configuration. Modify the questions and add extra sections to your markdown document by adding
# items to the extra_sections
---
questions:
  - "How did your development session go?"
  - "Did you learn anything new? If so, what did you learn?"
  - "What could have gone better?"
  - "What went well?"
other_section:
  - "Notes"
